apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: theanuragsachan/ws-chatapp-backend
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_URL
              value: "redis://redis:6379"
